# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbposter', '0002_entry_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='publish',
            new_name='public',
        ),
    ]
