# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbposter', '0003_auto_20170818_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='publish_to_fb_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(null=True, to='fbposter.Tag'),
        ),
    ]
