# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbposter', '0004_auto_20170819_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='publish_to_fb_date',
            new_name='post_to_fb_date',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='publish_to_fb_public',
            new_name='post_to_fb_public',
        ),
        migrations.AddField(
            model_name='entry',
            name='post_to_fb',
            field=models.BooleanField(default=False),
        ),
    ]
