# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbposter', '0005_auto_20170819_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='post_to_fb_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(to='fbposter.Tag'),
        ),
    ]
