# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbposter', '0006_auto_20170819_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='post_to_fb_actions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='post_to_fb_reachs',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
