# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbposter', '0007_auto_20170821_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
